import './globals.scss'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<code>RootLayout</code>
				{children}
			</body>
		</html>
	)
}

export default RootLayout